version: '2'

services:
  webserver:
    build: ./docker/webserver
    image: mvc_web
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - /Users/bruno/Projetos/simple-php-framework:/var/www
    links:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=db_mvc